[INFO] 01/18/2019 08:57:11 AM  " * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)"
[INFO] 01/18/2019 08:57:11 AM  " * Restarting with stat"
[WARNING] 01/18/2019 08:57:12 AM  " * Debugger is active!"
[INFO] 01/18/2019 08:57:12 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 08:57:16 AM  "127.0.0.1 - - [18/Jan/2019 08:57:16] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 08:57:16 AM  "127.0.0.1 - - [18/Jan/2019 08:57:16] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 08:57:16 AM  "127.0.0.1 - - [18/Jan/2019 08:57:16] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 08:57:16 AM  "127.0.0.1 - - [18/Jan/2019 08:57:16] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 08:57:16 AM  "127.0.0.1 - - [18/Jan/2019 08:57:16] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 08:57:16 AM  "127.0.0.1 - - [18/Jan/2019 08:57:16] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[ERROR] 01/18/2019 08:57:21 AM  "Exception on /swagger-ui.html/audit/audits [POST]"
Traceback (most recent call last):
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/archange/PycharmProjects/audit_manger/api.py", line 22, in post
    return fonction.create_context(),201
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 76, in create_context
    save_ong(json.dumps(context_to_mongo))
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 56, in save_ong
    return col.insert_one(context)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/collection.py", line 3317, in __call__
    self.__name)
TypeError: 'Collection' object is not callable. If you meant to call the 'insert_one' method on a 'Database' object it is failing because no such method exists.
[INFO] 01/18/2019 08:57:21 AM  "127.0.0.1 - - [18/Jan/2019 08:57:21] "POST /swagger-ui.html/audit/audits HTTP/1.1" 500 -"
[INFO] 01/18/2019 08:59:57 AM  " * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)"
[INFO] 01/18/2019 08:59:57 AM  " * Restarting with stat"
[WARNING] 01/18/2019 08:59:58 AM  " * Debugger is active!"
[INFO] 01/18/2019 08:59:58 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:00:03 AM  "127.0.0.1 - - [18/Jan/2019 09:00:03] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:00:03 AM  "127.0.0.1 - - [18/Jan/2019 09:00:03] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:00:03 AM  "127.0.0.1 - - [18/Jan/2019 09:00:03] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:00:03 AM  "127.0.0.1 - - [18/Jan/2019 09:00:03] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:00:03 AM  "127.0.0.1 - - [18/Jan/2019 09:00:03] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:00:03 AM  "127.0.0.1 - - [18/Jan/2019 09:00:03] "GET /swaggerui/favicon-16x16.png HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:00:03 AM  "127.0.0.1 - - [18/Jan/2019 09:00:03] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[ERROR] 01/18/2019 09:00:38 AM  "Exception on /swagger-ui.html/audit/audits [POST]"
Traceback (most recent call last):
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/archange/PycharmProjects/audit_manger/api.py", line 22, in post
    return fonction.create_context(),201
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 81, in create_context
    save_ong(context_to_mongo)
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 57, in save_ong
    return data_base.context.save(context)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/collection.py", line 3142, in save
    collation=collation)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/collection.py", line 851, in _update_retryable
    _update, session)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1247, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1576, in _tmp_session
    s = self._ensure_session(session)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1563, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1516, in __start_session
    server_session = self._get_server_session()
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1549, in _get_server_session
    return self._topology.get_server_session()
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/topology.py", line 427, in get_server_session
    None)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[INFO] 01/18/2019 09:00:38 AM  "127.0.0.1 - - [18/Jan/2019 09:00:38] "POST /swagger-ui.html/audit/audits HTTP/1.1" 500 -"
[INFO] 01/18/2019 09:01:21 AM  " * Detected change in '/home/archange/PycharmProjects/audit_manger/fonction.py', reloading"
[INFO] 01/18/2019 09:01:21 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:01:21 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:01:21 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:01:23 AM  " * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)"
[INFO] 01/18/2019 09:01:23 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:01:23 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:01:23 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:01:27 AM  "127.0.0.1 - - [18/Jan/2019 09:01:27] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:01:27 AM  "127.0.0.1 - - [18/Jan/2019 09:01:27] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:01:27 AM  "127.0.0.1 - - [18/Jan/2019 09:01:27] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:01:27 AM  "127.0.0.1 - - [18/Jan/2019 09:01:27] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:01:27 AM  "127.0.0.1 - - [18/Jan/2019 09:01:27] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:01:28 AM  "127.0.0.1 - - [18/Jan/2019 09:01:28] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[ERROR] 01/18/2019 09:02:02 AM  "Exception on /swagger-ui.html/audit/audits [POST]"
Traceback (most recent call last):
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/archange/PycharmProjects/audit_manger/api.py", line 22, in post
    return fonction.create_context(),201
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 81, in create_context
    save_ong(context_to_mongo)
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 57, in save_ong
    return data_base.context.save(context)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/collection.py", line 3142, in save
    collation=collation)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/collection.py", line 851, in _update_retryable
    _update, session)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1247, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1576, in _tmp_session
    s = self._ensure_session(session)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1563, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1516, in __start_session
    server_session = self._get_server_session()
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1549, in _get_server_session
    return self._topology.get_server_session()
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/topology.py", line 427, in get_server_session
    None)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:9200: timed out
[INFO] 01/18/2019 09:02:02 AM  "127.0.0.1 - - [18/Jan/2019 09:02:02] "POST /swagger-ui.html/audit/audits HTTP/1.1" 500 -"
[INFO] 01/18/2019 09:03:42 AM  " * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)"
[INFO] 01/18/2019 09:03:42 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:03:43 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:03:43 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:03:46 AM  "127.0.0.1 - - [18/Jan/2019 09:03:46] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:03:46 AM  "127.0.0.1 - - [18/Jan/2019 09:03:46] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:03:46 AM  "127.0.0.1 - - [18/Jan/2019 09:03:46] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:03:46 AM  "127.0.0.1 - - [18/Jan/2019 09:03:46] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:03:46 AM  "127.0.0.1 - - [18/Jan/2019 09:03:46] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:03:47 AM  "127.0.0.1 - - [18/Jan/2019 09:03:47] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[ERROR] 01/18/2019 09:04:21 AM  "Exception on /swagger-ui.html/audit/audits [POST]"
Traceback (most recent call last):
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/archange/PycharmProjects/audit_manger/api.py", line 22, in post
    return fonction.create_context(),201
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 81, in create_context
    save_ong(context_to_mongo)
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 57, in save_ong
    return data_base.context.save(context)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/collection.py", line 3142, in save
    collation=collation)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/collection.py", line 851, in _update_retryable
    _update, session)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1247, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1576, in _tmp_session
    s = self._ensure_session(session)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1563, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1516, in __start_session
    server_session = self._get_server_session()
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1549, in _get_server_session
    return self._topology.get_server_session()
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/topology.py", line 427, in get_server_session
    None)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:9200: timed out
[INFO] 01/18/2019 09:04:21 AM  "127.0.0.1 - - [18/Jan/2019 09:04:21] "POST /swagger-ui.html/audit/audits HTTP/1.1" 500 -"
[INFO] 01/18/2019 09:04:40 AM  " * Detected change in '/home/archange/PycharmProjects/audit_manger/fonction.py', reloading"
[INFO] 01/18/2019 09:04:40 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:04:40 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:04:40 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:04:42 AM  " * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)"
[INFO] 01/18/2019 09:04:42 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:04:42 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:04:42 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:04:45 AM  "127.0.0.1 - - [18/Jan/2019 09:04:45] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:04:45 AM  "127.0.0.1 - - [18/Jan/2019 09:04:45] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:04:45 AM  "127.0.0.1 - - [18/Jan/2019 09:04:45] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:04:45 AM  "127.0.0.1 - - [18/Jan/2019 09:04:45] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:04:45 AM  "127.0.0.1 - - [18/Jan/2019 09:04:45] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:04:46 AM  "127.0.0.1 - - [18/Jan/2019 09:04:46] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:04:50 AM  "127.0.0.1 - - [18/Jan/2019 09:04:50] "POST /swagger-ui.html/audit/audits HTTP/1.1" 201 -"
[INFO] 01/18/2019 09:05:06 AM  " * Detected change in '/home/archange/PycharmProjects/audit_manger/fonction.py', reloading"
[INFO] 01/18/2019 09:05:06 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:05:06 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:05:06 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:05:08 AM  "127.0.0.1 - - [18/Jan/2019 09:05:08] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:05:08 AM  "127.0.0.1 - - [18/Jan/2019 09:05:08] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:05:08 AM  "127.0.0.1 - - [18/Jan/2019 09:05:08] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:05:08 AM  "127.0.0.1 - - [18/Jan/2019 09:05:08] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:05:08 AM  "127.0.0.1 - - [18/Jan/2019 09:05:08] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:05:08 AM  "127.0.0.1 - - [18/Jan/2019 09:05:08] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:05:13 AM  "127.0.0.1 - - [18/Jan/2019 09:05:13] "POST /swagger-ui.html/audit/audits HTTP/1.1" 201 -"
[INFO] 01/18/2019 09:05:19 AM  "127.0.0.1 - - [18/Jan/2019 09:05:19] "POST /swagger-ui.html/audit/audits HTTP/1.1" 201 -"
[INFO] 01/18/2019 09:05:37 AM  " * Detected change in '/home/archange/PycharmProjects/audit_manger/fonction.py', reloading"
[INFO] 01/18/2019 09:05:37 AM  " * Restarting with stat"
[INFO] 01/18/2019 09:05:38 AM  " * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)"
[INFO] 01/18/2019 09:05:38 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:05:39 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:05:39 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:05:40 AM  "127.0.0.1 - - [18/Jan/2019 09:05:40] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:05:40 AM  "127.0.0.1 - - [18/Jan/2019 09:05:40] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:05:40 AM  "127.0.0.1 - - [18/Jan/2019 09:05:40] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:05:40 AM  "127.0.0.1 - - [18/Jan/2019 09:05:40] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:05:40 AM  "127.0.0.1 - - [18/Jan/2019 09:05:40] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:05:41 AM  "127.0.0.1 - - [18/Jan/2019 09:05:41] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[ERROR] 01/18/2019 09:05:44 AM  "Exception on /swagger-ui.html/audit/audits [POST]"
Traceback (most recent call last):
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/archange/PycharmProjects/audit_manger/api.py", line 22, in post
    return fonction.create_context(),201
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 81, in create_context
    save_ong(context_to_mongo)
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 61, in save_ong
    return col.insert_one(context)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/collection.py", line 3317, in __call__
    self.__name)
TypeError: 'Collection' object is not callable. If you meant to call the 'insert_one' method on a 'Database' object it is failing because no such method exists.
[INFO] 01/18/2019 09:05:44 AM  "127.0.0.1 - - [18/Jan/2019 09:05:44] "POST /swagger-ui.html/audit/audits HTTP/1.1" 500 -"
[INFO] 01/18/2019 09:08:43 AM  " * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)"
[INFO] 01/18/2019 09:08:43 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:08:44 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:08:44 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:08:46 AM  "127.0.0.1 - - [18/Jan/2019 09:08:46] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:08:46 AM  "127.0.0.1 - - [18/Jan/2019 09:08:46] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:08:46 AM  "127.0.0.1 - - [18/Jan/2019 09:08:46] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:08:46 AM  "127.0.0.1 - - [18/Jan/2019 09:08:46] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:08:46 AM  "127.0.0.1 - - [18/Jan/2019 09:08:46] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:08:47 AM  "127.0.0.1 - - [18/Jan/2019 09:08:47] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[ERROR] 01/18/2019 09:08:50 AM  "Exception on /swagger-ui.html/audit/audits [POST]"
Traceback (most recent call last):
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/archange/PycharmProjects/audit_manger/api.py", line 22, in post
    return fonction.create_context(),201
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 82, in create_context
    save_ong(context_to_mongo)
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 62, in save_ong
    return col.save(context)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/collection.py", line 3317, in __call__
    self.__name)
TypeError: 'Collection' object is not callable. If you meant to call the 'save' method on a 'Database' object it is failing because no such method exists.
[INFO] 01/18/2019 09:08:50 AM  "127.0.0.1 - - [18/Jan/2019 09:08:50] "POST /swagger-ui.html/audit/audits HTTP/1.1" 500 -"
[INFO] 01/18/2019 09:09:44 AM  " * Detected change in '/home/archange/PycharmProjects/audit_manger/fonction.py', reloading"
[INFO] 01/18/2019 09:09:44 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:09:44 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:09:44 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:09:46 AM  " * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)"
[INFO] 01/18/2019 09:09:46 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:09:46 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:09:46 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:09:47 AM  "127.0.0.1 - - [18/Jan/2019 09:09:47] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:09:47 AM  "127.0.0.1 - - [18/Jan/2019 09:09:47] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:09:47 AM  "127.0.0.1 - - [18/Jan/2019 09:09:47] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:09:47 AM  "127.0.0.1 - - [18/Jan/2019 09:09:47] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:09:47 AM  "127.0.0.1 - - [18/Jan/2019 09:09:47] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:09:48 AM  "127.0.0.1 - - [18/Jan/2019 09:09:48] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:09:51 AM  "127.0.0.1 - - [18/Jan/2019 09:09:51] "POST /swagger-ui.html/audit/audits HTTP/1.1" 201 -"
[INFO] 01/18/2019 09:12:07 AM  " * Detected change in '/home/archange/PycharmProjects/audit_manger/fonction.py', reloading"
[INFO] 01/18/2019 09:12:07 AM  " * Restarting with stat"
[INFO] 01/18/2019 09:12:09 AM  " * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)"
[INFO] 01/18/2019 09:12:09 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:12:09 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:12:09 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:12:11 AM  "127.0.0.1 - - [18/Jan/2019 09:12:11] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:12:11 AM  "127.0.0.1 - - [18/Jan/2019 09:12:11] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:12:11 AM  "127.0.0.1 - - [18/Jan/2019 09:12:11] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:12:11 AM  "127.0.0.1 - - [18/Jan/2019 09:12:11] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:12:11 AM  "127.0.0.1 - - [18/Jan/2019 09:12:11] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:12:11 AM  "127.0.0.1 - - [18/Jan/2019 09:12:11] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[ERROR] 01/18/2019 09:12:15 AM  "Exception on /swagger-ui.html/audit/audits [POST]"
Traceback (most recent call last):
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 329, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 350, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'MongoClient' is not JSON serializable
[INFO] 01/18/2019 09:12:15 AM  "127.0.0.1 - - [18/Jan/2019 09:12:15] "POST /swagger-ui.html/audit/audits HTTP/1.1" 500 -"
[ERROR] 01/18/2019 09:12:56 AM  "Exception on /swagger-ui.html/audit/audits [POST]"
Traceback (most recent call last):
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 329, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 350, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'MongoClient' is not JSON serializable
[INFO] 01/18/2019 09:12:56 AM  "127.0.0.1 - - [18/Jan/2019 09:12:56] "POST /swagger-ui.html/audit/audits HTTP/1.1" 500 -"
[INFO] 01/18/2019 09:13:37 AM  " * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)"
[INFO] 01/18/2019 09:13:37 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:13:38 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:13:38 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:13:39 AM  "127.0.0.1 - - [18/Jan/2019 09:13:39] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:13:39 AM  "127.0.0.1 - - [18/Jan/2019 09:13:39] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:13:39 AM  "127.0.0.1 - - [18/Jan/2019 09:13:39] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:13:39 AM  "127.0.0.1 - - [18/Jan/2019 09:13:39] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:13:39 AM  "127.0.0.1 - - [18/Jan/2019 09:13:39] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:13:40 AM  "127.0.0.1 - - [18/Jan/2019 09:13:40] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:13:45 AM  "127.0.0.1 - - [18/Jan/2019 09:13:45] "POST /swagger-ui.html/audit/audits HTTP/1.1" 201 -"
[INFO] 01/18/2019 09:14:43 AM  " * Detected change in '/home/archange/PycharmProjects/audit_manger/fonction.py', reloading"
[INFO] 01/18/2019 09:14:43 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:14:43 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:14:43 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:14:45 AM  " * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)"
[INFO] 01/18/2019 09:14:45 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:14:46 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:14:46 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:14:47 AM  "127.0.0.1 - - [18/Jan/2019 09:14:47] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:14:47 AM  "127.0.0.1 - - [18/Jan/2019 09:14:47] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:14:47 AM  "127.0.0.1 - - [18/Jan/2019 09:14:47] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:14:47 AM  "127.0.0.1 - - [18/Jan/2019 09:14:47] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:14:47 AM  "127.0.0.1 - - [18/Jan/2019 09:14:47] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:14:47 AM  "127.0.0.1 - - [18/Jan/2019 09:14:47] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:14:51 AM  "127.0.0.1 - - [18/Jan/2019 09:14:51] "POST /swagger-ui.html/audit/audits HTTP/1.1" 201 -"
[INFO] 01/18/2019 09:17:20 AM  " * Detected change in '/home/archange/PycharmProjects/audit_manger/fonction.py', reloading"
[INFO] 01/18/2019 09:17:20 AM  " * Restarting with stat"
[WARNING] 01/18/2019 09:17:21 AM  " * Debugger is active!"
[INFO] 01/18/2019 09:17:21 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 09:25:31 AM  "127.0.0.1 - - [18/Jan/2019 09:25:31] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:25:31 AM  "127.0.0.1 - - [18/Jan/2019 09:25:31] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:25:31 AM  "127.0.0.1 - - [18/Jan/2019 09:25:31] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:25:31 AM  "127.0.0.1 - - [18/Jan/2019 09:25:31] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:25:31 AM  "127.0.0.1 - - [18/Jan/2019 09:25:31] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 09:25:31 AM  "127.0.0.1 - - [18/Jan/2019 09:25:31] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[INFO] 01/18/2019 09:25:35 AM  "127.0.0.1 - - [18/Jan/2019 09:25:35] "POST /swagger-ui.html/audit/audits HTTP/1.1" 201 -"
[INFO] 01/18/2019 11:33:54 AM  " * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)"
[INFO] 01/18/2019 11:33:54 AM  " * Restarting with stat"
[WARNING] 01/18/2019 11:33:55 AM  " * Debugger is active!"
[INFO] 01/18/2019 11:33:55 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 11:34:24 AM  "127.0.0.1 - - [18/Jan/2019 11:34:24] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 11:34:24 AM  "127.0.0.1 - - [18/Jan/2019 11:34:24] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -"
[INFO] 01/18/2019 11:34:24 AM  "127.0.0.1 - - [18/Jan/2019 11:34:24] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -"
[INFO] 01/18/2019 11:34:25 AM  "127.0.0.1 - - [18/Jan/2019 11:34:25] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[INFO] 01/18/2019 11:34:31 AM  "127.0.0.1 - - [18/Jan/2019 11:34:31] "POST /swagger-ui.html/audit/audits HTTP/1.1" 201 -"
[INFO] 01/18/2019 11:35:55 AM  " * Detected change in '/home/archange/PycharmProjects/audit_manger/fonction.py', reloading"
[INFO] 01/18/2019 11:35:55 AM  " * Restarting with stat"
[WARNING] 01/18/2019 11:35:55 AM  " * Debugger is active!"
[INFO] 01/18/2019 11:35:55 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 11:35:58 AM  " * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)"
[INFO] 01/18/2019 11:35:58 AM  " * Restarting with stat"
[WARNING] 01/18/2019 11:35:59 AM  " * Debugger is active!"
[INFO] 01/18/2019 11:35:59 AM  " * Debugger PIN: 867-688-660"
[INFO] 01/18/2019 11:36:01 AM  "127.0.0.1 - - [18/Jan/2019 11:36:01] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/18/2019 11:36:01 AM  "127.0.0.1 - - [18/Jan/2019 11:36:01] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 11:36:01 AM  "127.0.0.1 - - [18/Jan/2019 11:36:01] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 11:36:01 AM  "127.0.0.1 - - [18/Jan/2019 11:36:01] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -"
[INFO] 01/18/2019 11:36:01 AM  "127.0.0.1 - - [18/Jan/2019 11:36:01] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -"
[INFO] 01/18/2019 11:36:01 AM  "127.0.0.1 - - [18/Jan/2019 11:36:01] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[INFO] 01/18/2019 11:36:06 AM  "127.0.0.1 - - [18/Jan/2019 11:36:06] "POST /swagger-ui.html/audit/audits HTTP/1.1" 201 -"
[INFO] 01/24/2019 08:18:48 AM  " * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)"
[INFO] 01/24/2019 08:19:44 AM  "127.0.0.1 - - [24/Jan/2019 08:19:44] "GET /swagger-ui.html HTTP/1.1" 301 -"
[INFO] 01/24/2019 08:19:44 AM  "127.0.0.1 - - [24/Jan/2019 08:19:44] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 01/24/2019 08:19:44 AM  "127.0.0.1 - - [24/Jan/2019 08:19:44] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -"
[INFO] 01/24/2019 08:19:44 AM  "127.0.0.1 - - [24/Jan/2019 08:19:44] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -"
[INFO] 01/24/2019 08:19:44 AM  "127.0.0.1 - - [24/Jan/2019 08:19:44] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -"
[INFO] 01/24/2019 08:19:44 AM  "127.0.0.1 - - [24/Jan/2019 08:19:44] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -"
[INFO] 01/24/2019 08:19:45 AM  "127.0.0.1 - - [24/Jan/2019 08:19:45] "GET /swaggerui/favicon-16x16.png HTTP/1.1" 200 -"
[INFO] 01/24/2019 08:19:45 AM  "127.0.0.1 - - [24/Jan/2019 08:19:45] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[INFO] 01/24/2019 08:20:19 AM  "127.0.0.1 - - [24/Jan/2019 08:20:19] "GET /audit HTTP/1.1" 404 -"
[INFO] 01/24/2019 08:20:19 AM  "127.0.0.1 - - [24/Jan/2019 08:20:19] "GET /favicon.ico HTTP/1.1" 404 -"
[INFO] 01/24/2019 08:21:10 AM  "127.0.0.1 - - [24/Jan/2019 08:21:10] "GET /api HTTP/1.1" 404 -"
[INFO] 02/01/2019 02:49:49 PM  " * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)"
[INFO] 02/01/2019 02:50:49 PM  "127.0.0.1 - - [01/Feb/2019 14:50:49] "GET /swagger-ui.html HTTP/1.1" 301 -"
[INFO] 02/01/2019 02:50:49 PM  "127.0.0.1 - - [01/Feb/2019 14:50:49] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 02/01/2019 02:50:49 PM  "127.0.0.1 - - [01/Feb/2019 14:50:49] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -"
[INFO] 02/01/2019 02:50:49 PM  "127.0.0.1 - - [01/Feb/2019 14:50:49] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -"
[INFO] 02/01/2019 02:50:49 PM  "127.0.0.1 - - [01/Feb/2019 14:50:49] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -"
[INFO] 02/01/2019 02:50:49 PM  "127.0.0.1 - - [01/Feb/2019 14:50:49] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -"
[INFO] 02/01/2019 02:50:50 PM  "127.0.0.1 - - [01/Feb/2019 14:50:50] "GET /swaggerui/favicon-16x16.png HTTP/1.1" 200 -"
[INFO] 02/01/2019 02:50:50 PM  "127.0.0.1 - - [01/Feb/2019 14:50:50] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[ERROR] 02/01/2019 02:51:35 PM  "Exception on /swagger-ui.html/audit/audits [POST]"
Traceback (most recent call last):
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/archange/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/archange/.local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/archange/PycharmProjects/audit_manger/api.py", line 22, in post
    return fonction.create_context(),201
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 88, in create_context
    save_ong(context_to_mongo)
  File "/home/archange/PycharmProjects/audit_manger/fonction.py", line 62, in save_ong
    return data_base.audit.save(audit)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/collection.py", line 3142, in save
    collation=collation)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/collection.py", line 851, in _update_retryable
    _update, session)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1247, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1576, in _tmp_session
    s = self._ensure_session(session)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1563, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1516, in __start_session
    server_session = self._get_server_session()
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1549, in _get_server_session
    return self._topology.get_server_session()
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/topology.py", line 427, in get_server_session
    None)
  File "/home/archange/.local/lib/python3.6/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[INFO] 02/01/2019 02:51:35 PM  "127.0.0.1 - - [01/Feb/2019 14:51:35] "POST /swagger-ui.html/audit/audits HTTP/1.1" 500 -"
[INFO] 02/01/2019 02:52:20 PM  "127.0.0.1 - - [01/Feb/2019 14:52:20] "POST /swagger-ui.html/audit/audits HTTP/1.1" 201 -"
[INFO] 02/01/2019 03:32:51 PM  " * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)"
[INFO] 02/01/2019 03:33:06 PM  "127.0.0.1 - - [01/Feb/2019 15:33:06] "GET /swagger-ui.html/ HTTP/1.1" 200 -"
[INFO] 02/01/2019 03:33:06 PM  "127.0.0.1 - - [01/Feb/2019 15:33:06] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -"
[INFO] 02/01/2019 03:33:06 PM  "127.0.0.1 - - [01/Feb/2019 15:33:06] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -"
[INFO] 02/01/2019 03:33:06 PM  "127.0.0.1 - - [01/Feb/2019 15:33:06] "GET /swaggerui/favicon-16x16.png HTTP/1.1" 200 -"
[INFO] 02/01/2019 03:33:07 PM  "127.0.0.1 - - [01/Feb/2019 15:33:07] "GET /swagger-ui.html/swagger.json HTTP/1.1" 200 -"
[INFO] 02/01/2019 03:33:14 PM  "127.0.0.1 - - [01/Feb/2019 15:33:14] "POST /swagger-ui.html/audit/audits HTTP/1.1" 201 -"
[INFO] 02/01/2019 03:41:06 PM  "127.0.0.1 - - [01/Feb/2019 15:41:06] "POST /swagger-ui.html/audit/audits HTTP/1.1" 201 -"
[INFO] 02/01/2019 03:42:08 PM  "127.0.0.1 - - [01/Feb/2019 15:42:08] "POST /swagger-ui.html/audit/audits HTTP/1.1" 201 -"
